language: 'node_js'

node_js: '14'

git:
  depth: 3

branches:
  only:
    - main

script:
  - yarn test

deploy:
  provider: heroku
  skin-cleanup: true
  keep-history: true
  api_key: $API_KEY_HEROKU
  app: image-extractor-api
  on:
    - main
